steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package', '-B', '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/airline-simulato-1576656353216/runner', '.']
  dir: 'runner'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/airline-simulato-1576656353216/flighttracker-service', '.']
  dir: 'flighttracker-service'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/airline-simulato-1576656353216/booking-service', '.']
  dir: 'booking-service'
images: ['gcr.io/airline-simulato-1576656353216/runner', 'gcr.io/airline-simulato-1576656353216/flighttracker-service', 'gcr.io/airline-simulato-1576656353216/booking-service']
