steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package', '-B', '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/airline-simulato-1576656353216/runner', './runner']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/airline-simulato-1576656353216/flighttracker-service', './flighttracker-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/airline-simulato-1576656353216/booking-service', './booking-service']
  dir: 'runner'
images: ['gcr.io/airline-simulato-1576656353216/runner', 'gcr.io/airline-simulato-1576656353216/flighttracker-service', 'gcr.io/airline-simulato-1576656353216/booking-service']
