steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/airline-simulator/runner', '.']
  dir: 'runner'
images: ['gcr.io/airline-simulator/runner']
