version: '3'
services:
  axon-server:
    image: axoniq/axonserver
    environment:
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true
    ports:
      - "8024:8024"
      - "8124:8124"
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=airlinesim
      - POSTGRES_PASSWORD=airlinesim
      - POSTGRES_DB=airlinesim
    ports:
      - "5432:5432"
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment: 
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"